---
name: "create release"

on:
  push:
    branches:
      - "master"

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  pre-release:
    name: "create nightly release"
    runs-on: "ubuntu-latest"
    permissions: write-all

    steps:
      - uses: "actions/checkout@v7"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Libretube Nightly Build"
          files: |
            checksums
            app-debug-signed.apk
